config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :plays
  root 'plays#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :plays
end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :plays
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: [:show, :edit, :update, :destroy]

  def index
    @plays = Play.all.order("created_at DESC")
  end

  def new
    @play = current_user.plays.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]
    if @play.save
      redirect_to @play
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
    @play.category_id = params[:category_id]
    if @play.update(play_params)
      redirect_to @play
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

    def find_play
      @play = Play.find(params[:id])
    end

    def play_params
      params.require(:play).permit(:title, :description, :director)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Broadway
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{ :type => "button", "data-toggle" => "collapse", "data-target" =>"#main-nav", "aria-expanded" => "false" }
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
          = link_to "Broadway", root_path, class: "navbar-brand"
        %ul.nav.navbar-nav
          - if user_signed_in?
            %li= link_to "Add a play", new_play_path
        %ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
          - else
            %li= link_to "Sign In", new_user_session_path
            %li= link_to "Sign Up", new_user_registration_path


    .container

      - flash.each do |name,msg|
        =content_tag :div, msg, class: "alert alert-info"

      = yield

app/views/plays/_form.html.haml
= simple_form_for @play do |f|
  = select_tag(:category_id, options_for_select(@categories), :prompt => "Select Category")
  = f.input :title, label: "Play Title"
  = f.input :description
  = f.input :director
  = f.button :submit

app/views/plays/edit.html.haml
%h1 Edit Play
= render 'form'

app/views/plays/index.html.haml
%h1 Placeholder
- @plays.each do |play|
  %h2= link_to play.title, play_path(play)

app/views/plays/new.html.haml
%h1 New Broadway Play
= render 'form'

app/views/plays/show.html.haml
%h2= @play.title
%h3= @play.director
%h4= @play.category.name
%p= @play.description
.links.btn-group
  = link_to "Back", root_path, class: "btn btn-default"
  -if user_signed_in? && current_user.id == @play.user_id
    = link_to "Edit", edit_play_path, class: "btn btn-info"
    = link_to "Delete", play_path(@play), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure"}